kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: iscsi-targetd-vg-targetd
provisioner: iscsi-targetd
parameters:
  targetPortal: 192.168.101.6
  iqn: iqn.1998-01.com.vmware.52a907bd52248412-6f58968352fe26af
  iscsiInterface: default
  volumeGroup: vg-targetd
  initiators: iqn.2019-01.com.example:node1, iqn.2019-01.com.example:node2
  chapAuthDiscovery: "false"
  chapAuthSession: "false"


kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-claim
spec:
  storageClassName: "iscsi-targetd-vg-targetd"
  accessModes:
  - ReadWriteOnce
  resources:
requests:
  storage: 100Mi