version: "3"

services:
  nexus:
    image: sonatype/nexus3
    restart: always
    container_name: nexus
    ports:
     -  8081:8081
     -  8080:8080
    networks:
     - app
    volumes:
     - ${PWD}/nexus-data/:/nexus-data/


networks:
  app:
